/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tags', 'model/Videodetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tags'), require('./Videodetails'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.Media = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Tags, root.CrowdemotionApiClientJs.Videodetails);
  }
}(this, function(ApiClient, Tags, Videodetails) {
  'use strict';




  /**
   * The Media model module.
   * @module model/Media
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Media</code>.
   * @alias module:model/Media
   * @class
   * @param id {Integer} 
   * @param name {String} 
   * @param mediaPath {String} 
   * @param path {String} 
   * @param researchId {Integer} 
   * @param timeCreated {Date} 
   * @param lengthMS {Integer} 
   * @param length {Integer} 
   * @param videoOrder {Integer} 
   * @param tags {Array.<module:model/Tags>} 
   * @param presignedUrl {String} 
   * @param isStored {Boolean} 
   * @param isURL {Boolean} 
   * @param isYouTube {Boolean} 
   * @param videodetails {module:model/Videodetails} 
   */
  var exports = function(id, name, mediaPath, path, researchId, timeCreated, lengthMS, length, videoOrder, tags, presignedUrl, isStored, isURL, isYouTube, videodetails) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['mediaPath'] = mediaPath;
    _this['path'] = path;
    _this['researchId'] = researchId;
    _this['timeCreated'] = timeCreated;
    _this['lengthMS'] = lengthMS;
    _this['length'] = length;
    _this['videoOrder'] = videoOrder;
    _this['tags'] = tags;
    _this['presignedUrl'] = presignedUrl;
    _this['isStored'] = isStored;
    _this['isURL'] = isURL;
    _this['isYouTube'] = isYouTube;
    _this['videodetails'] = videodetails;
  };

  /**
   * Constructs a <code>Media</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Media} obj Optional instance to populate.
   * @return {module:model/Media} The populated <code>Media</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('mediaPath')) {
        obj['mediaPath'] = ApiClient.convertToType(data['mediaPath'], 'String');
      }
      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('researchId')) {
        obj['researchId'] = ApiClient.convertToType(data['researchId'], 'Integer');
      }
      if (data.hasOwnProperty('timeCreated')) {
        obj['timeCreated'] = ApiClient.convertToType(data['timeCreated'], 'Date');
      }
      if (data.hasOwnProperty('lengthMS')) {
        obj['lengthMS'] = ApiClient.convertToType(data['lengthMS'], 'Integer');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'Integer');
      }
      if (data.hasOwnProperty('videoOrder')) {
        obj['videoOrder'] = ApiClient.convertToType(data['videoOrder'], 'Integer');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [Tags]);
      }
      if (data.hasOwnProperty('presignedUrl')) {
        obj['presignedUrl'] = ApiClient.convertToType(data['presignedUrl'], 'String');
      }
      if (data.hasOwnProperty('isStored')) {
        obj['isStored'] = ApiClient.convertToType(data['isStored'], 'Boolean');
      }
      if (data.hasOwnProperty('isURL')) {
        obj['isURL'] = ApiClient.convertToType(data['isURL'], 'Boolean');
      }
      if (data.hasOwnProperty('isYouTube')) {
        obj['isYouTube'] = ApiClient.convertToType(data['isYouTube'], 'Boolean');
      }
      if (data.hasOwnProperty('videodetails')) {
        obj['videodetails'] = Videodetails.constructFromObject(data['videodetails']);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 
   * @member {String} mediaPath
   */
  exports.prototype['mediaPath'] = undefined;
  /**
   * 
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * 
   * @member {Integer} researchId
   */
  exports.prototype['researchId'] = undefined;
  /**
   * 
   * @member {Date} timeCreated
   */
  exports.prototype['timeCreated'] = undefined;
  /**
   * 
   * @member {Integer} lengthMS
   */
  exports.prototype['lengthMS'] = undefined;
  /**
   * 
   * @member {Integer} length
   */
  exports.prototype['length'] = undefined;
  /**
   * 
   * @member {Integer} videoOrder
   */
  exports.prototype['videoOrder'] = undefined;
  /**
   * @member {Array.<module:model/Tags>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * 
   * @member {String} presignedUrl
   */
  exports.prototype['presignedUrl'] = undefined;
  /**
   * 
   * @member {Boolean} isStored
   */
  exports.prototype['isStored'] = undefined;
  /**
   * 
   * @member {Boolean} isURL
   */
  exports.prototype['isURL'] = undefined;
  /**
   * 
   * @member {Boolean} isYouTube
   */
  exports.prototype['isYouTube'] = undefined;
  /**
   * @member {module:model/Videodetails} videodetails
   */
  exports.prototype['videodetails'] = undefined;



  return exports;
}));


