/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Tags', 'model/Videodetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Tags'), require('./Videodetails'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.MediaCreation = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Tags, root.CrowdemotionApiClientJs.Videodetails);
  }
}(this, function(ApiClient, Tags, Videodetails) {
  'use strict';




  /**
   * The MediaCreation model module.
   * @module model/MediaCreation
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>MediaCreation</code>.
   * @alias module:model/MediaCreation
   * @class
   * @param name {String} 
   * @param mediaPath {String} 
   * @param researchId {Integer} 
   * @param length {Integer} 
   * @param videoOrder {Integer} 
   * @param tags {Array.<module:model/Tags>} 
   * @param videodetails {module:model/Videodetails} 
   */
  var exports = function(name, mediaPath, researchId, length, videoOrder, tags, videodetails) {
    var _this = this;

    _this['name'] = name;
    _this['mediaPath'] = mediaPath;
    _this['research_id'] = researchId;
    _this['length'] = length;
    _this['videoOrder'] = videoOrder;
    _this['tags'] = tags;
    _this['videodetails'] = videodetails;
  };

  /**
   * Constructs a <code>MediaCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaCreation} obj Optional instance to populate.
   * @return {module:model/MediaCreation} The populated <code>MediaCreation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('mediaPath')) {
        obj['mediaPath'] = ApiClient.convertToType(data['mediaPath'], 'String');
      }
      if (data.hasOwnProperty('research_id')) {
        obj['research_id'] = ApiClient.convertToType(data['research_id'], 'Integer');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'Integer');
      }
      if (data.hasOwnProperty('videoOrder')) {
        obj['videoOrder'] = ApiClient.convertToType(data['videoOrder'], 'Integer');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [Tags]);
      }
      if (data.hasOwnProperty('videodetails')) {
        obj['videodetails'] = Videodetails.constructFromObject(data['videodetails']);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * 
   * @member {String} mediaPath
   */
  exports.prototype['mediaPath'] = undefined;
  /**
   * 
   * @member {Integer} research_id
   */
  exports.prototype['research_id'] = undefined;
  /**
   * 
   * @member {Integer} length
   */
  exports.prototype['length'] = undefined;
  /**
   * 
   * @member {Integer} videoOrder
   */
  exports.prototype['videoOrder'] = undefined;
  /**
   * @member {Array.<module:model/Tags>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {module:model/Videodetails} videodetails
   */
  exports.prototype['videodetails'] = undefined;



  return exports;
}));


