/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.ResearchCreation = factory(root.CrowdemotionApiClientJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ResearchCreation model module.
   * @module model/ResearchCreation
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>ResearchCreation</code>.
   * @alias module:model/ResearchCreation
   * @class
   * @param title {String} 
   * @param description {String} 
   * @param ready {Boolean} 
   * @param complete {Boolean} 
   * @param archived {Boolean} 
   * @param outgoingUrl {String} 
   * @param customData {String} 
   */
  var exports = function(title, description, ready, complete, archived, outgoingUrl, customData) {
    var _this = this;

    _this['title'] = title;
    _this['description'] = description;
    _this['ready'] = ready;
    _this['complete'] = complete;
    _this['archived'] = archived;
    _this['outgoingUrl'] = outgoingUrl;
    _this['customData'] = customData;
  };

  /**
   * Constructs a <code>ResearchCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResearchCreation} obj Optional instance to populate.
   * @return {module:model/ResearchCreation} The populated <code>ResearchCreation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('ready')) {
        obj['ready'] = ApiClient.convertToType(data['ready'], 'Boolean');
      }
      if (data.hasOwnProperty('complete')) {
        obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
      }
      if (data.hasOwnProperty('archived')) {
        obj['archived'] = ApiClient.convertToType(data['archived'], 'Boolean');
      }
      if (data.hasOwnProperty('outgoingUrl')) {
        obj['outgoingUrl'] = ApiClient.convertToType(data['outgoingUrl'], 'String');
      }
      if (data.hasOwnProperty('customData')) {
        obj['customData'] = ApiClient.convertToType(data['customData'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * 
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * 
   * @member {Boolean} ready
   */
  exports.prototype['ready'] = undefined;
  /**
   * 
   * @member {Boolean} complete
   */
  exports.prototype['complete'] = undefined;
  /**
   * 
   * @member {Boolean} archived
   */
  exports.prototype['archived'] = undefined;
  /**
   * 
   * @member {String} outgoingUrl
   */
  exports.prototype['outgoingUrl'] = undefined;
  /**
   * 
   * @member {String} customData
   */
  exports.prototype['customData'] = undefined;



  return exports;
}));


