/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Stats'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Stats'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.Research = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Stats);
  }
}(this, function(ApiClient, Stats) {
  'use strict';




  /**
   * The Research model module.
   * @module model/Research
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Research</code>.
   * @alias module:model/Research
   * @class
   * @param id {Integer} 
   * @param timeCreated {Date} 
   * @param uuid {String} 
   * @param key {String} 
   * @param title {String} 
   * @param description {String} 
   * @param ready {Boolean} 
   * @param complete {Boolean} 
   * @param archived {Boolean} 
   * @param outgoingUrl {String} 
   * @param customData {String} 
   * @param ownerId {Integer} 
   * @param companyId {Integer} 
   * @param stats {module:model/Stats} 
   */
  var exports = function(id, timeCreated, uuid, key, title, description, ready, complete, archived, outgoingUrl, customData, ownerId, companyId, stats) {
    var _this = this;

    _this['id'] = id;
    _this['timeCreated'] = timeCreated;
    _this['uuid'] = uuid;
    _this['key'] = key;
    _this['title'] = title;
    _this['description'] = description;
    _this['ready'] = ready;
    _this['complete'] = complete;
    _this['archived'] = archived;
    _this['outgoingUrl'] = outgoingUrl;
    _this['customData'] = customData;
    _this['owner_id'] = ownerId;
    _this['company_id'] = companyId;
    _this['stats'] = stats;
  };

  /**
   * Constructs a <code>Research</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Research} obj Optional instance to populate.
   * @return {module:model/Research} The populated <code>Research</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('timeCreated')) {
        obj['timeCreated'] = ApiClient.convertToType(data['timeCreated'], 'Date');
      }
      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('ready')) {
        obj['ready'] = ApiClient.convertToType(data['ready'], 'Boolean');
      }
      if (data.hasOwnProperty('complete')) {
        obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
      }
      if (data.hasOwnProperty('archived')) {
        obj['archived'] = ApiClient.convertToType(data['archived'], 'Boolean');
      }
      if (data.hasOwnProperty('outgoingUrl')) {
        obj['outgoingUrl'] = ApiClient.convertToType(data['outgoingUrl'], 'String');
      }
      if (data.hasOwnProperty('customData')) {
        obj['customData'] = ApiClient.convertToType(data['customData'], 'String');
      }
      if (data.hasOwnProperty('owner_id')) {
        obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Integer');
      }
      if (data.hasOwnProperty('company_id')) {
        obj['company_id'] = ApiClient.convertToType(data['company_id'], 'Integer');
      }
      if (data.hasOwnProperty('stats')) {
        obj['stats'] = Stats.constructFromObject(data['stats']);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * 
   * @member {Date} timeCreated
   */
  exports.prototype['timeCreated'] = undefined;
  /**
   * 
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * 
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * 
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * 
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * 
   * @member {Boolean} ready
   */
  exports.prototype['ready'] = undefined;
  /**
   * 
   * @member {Boolean} complete
   */
  exports.prototype['complete'] = undefined;
  /**
   * 
   * @member {Boolean} archived
   */
  exports.prototype['archived'] = undefined;
  /**
   * 
   * @member {String} outgoingUrl
   */
  exports.prototype['outgoingUrl'] = undefined;
  /**
   * 
   * @member {String} customData
   */
  exports.prototype['customData'] = undefined;
  /**
   * 
   * @member {Integer} owner_id
   */
  exports.prototype['owner_id'] = undefined;
  /**
   * 
   * @member {Integer} company_id
   */
  exports.prototype['company_id'] = undefined;
  /**
   * @member {module:model/Stats} stats
   */
  exports.prototype['stats'] = undefined;



  return exports;
}));


