/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.Status = factory(root.CrowdemotionApiClientJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Status model module.
   * @module model/Status
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Status</code>.
   * @alias module:model/Status
   * @class
   * @param uploadStatus {String} 
   * @param privacyStatus {String} 
   * @param license {String} 
   * @param embeddable {String} 
   * @param publicStatsViewable {String} 
   */
  var exports = function(uploadStatus, privacyStatus, license, embeddable, publicStatsViewable) {
    var _this = this;

    _this['uploadStatus'] = uploadStatus;
    _this['privacyStatus'] = privacyStatus;
    _this['license'] = license;
    _this['embeddable'] = embeddable;
    _this['publicStatsViewable'] = publicStatsViewable;
  };

  /**
   * Constructs a <code>Status</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Status} obj Optional instance to populate.
   * @return {module:model/Status} The populated <code>Status</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uploadStatus')) {
        obj['uploadStatus'] = ApiClient.convertToType(data['uploadStatus'], 'String');
      }
      if (data.hasOwnProperty('privacyStatus')) {
        obj['privacyStatus'] = ApiClient.convertToType(data['privacyStatus'], 'String');
      }
      if (data.hasOwnProperty('license')) {
        obj['license'] = ApiClient.convertToType(data['license'], 'String');
      }
      if (data.hasOwnProperty('embeddable')) {
        obj['embeddable'] = ApiClient.convertToType(data['embeddable'], 'String');
      }
      if (data.hasOwnProperty('publicStatsViewable')) {
        obj['publicStatsViewable'] = ApiClient.convertToType(data['publicStatsViewable'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} uploadStatus
   */
  exports.prototype['uploadStatus'] = undefined;
  /**
   * 
   * @member {String} privacyStatus
   */
  exports.prototype['privacyStatus'] = undefined;
  /**
   * 
   * @member {String} license
   */
  exports.prototype['license'] = undefined;
  /**
   * 
   * @member {String} embeddable
   */
  exports.prototype['embeddable'] = undefined;
  /**
   * 
   * @member {String} publicStatsViewable
   */
  exports.prototype['publicStatsViewable'] = undefined;



  return exports;
}));


