/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.Statistics = factory(root.CrowdemotionApiClientJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Statistics model module.
   * @module model/Statistics
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Statistics</code>.
   * @alias module:model/Statistics
   * @class
   * @param viewCount {Integer} 
   * @param likeCount {Integer} 
   * @param dislikeCount {Integer} 
   * @param favoriteCount {Integer} 
   * @param commentCount {Integer} 
   */
  var exports = function(viewCount, likeCount, dislikeCount, favoriteCount, commentCount) {
    var _this = this;

    _this['viewCount'] = viewCount;
    _this['likeCount'] = likeCount;
    _this['dislikeCount'] = dislikeCount;
    _this['favoriteCount'] = favoriteCount;
    _this['commentCount'] = commentCount;
  };

  /**
   * Constructs a <code>Statistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Statistics} obj Optional instance to populate.
   * @return {module:model/Statistics} The populated <code>Statistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('viewCount')) {
        obj['viewCount'] = ApiClient.convertToType(data['viewCount'], 'Integer');
      }
      if (data.hasOwnProperty('likeCount')) {
        obj['likeCount'] = ApiClient.convertToType(data['likeCount'], 'Integer');
      }
      if (data.hasOwnProperty('dislikeCount')) {
        obj['dislikeCount'] = ApiClient.convertToType(data['dislikeCount'], 'Integer');
      }
      if (data.hasOwnProperty('favoriteCount')) {
        obj['favoriteCount'] = ApiClient.convertToType(data['favoriteCount'], 'Integer');
      }
      if (data.hasOwnProperty('commentCount')) {
        obj['commentCount'] = ApiClient.convertToType(data['commentCount'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Integer} viewCount
   */
  exports.prototype['viewCount'] = undefined;
  /**
   * 
   * @member {Integer} likeCount
   */
  exports.prototype['likeCount'] = undefined;
  /**
   * 
   * @member {Integer} dislikeCount
   */
  exports.prototype['dislikeCount'] = undefined;
  /**
   * 
   * @member {Integer} favoriteCount
   */
  exports.prototype['favoriteCount'] = undefined;
  /**
   * 
   * @member {Integer} commentCount
   */
  exports.prototype['commentCount'] = undefined;



  return exports;
}));


