/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.Timeseries = factory(root.CrowdemotionApiClientJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Timeseries model module.
   * @module model/Timeseries
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>Timeseries</code>.
   * @alias module:model/Timeseries
   * @class
   * @param responseId {Integer} 
   * @param metricId {Integer} 
   * @param metricName {String} 
   * @param startIndex {Integer} 
   * @param endIndex {Integer} 
   * @param stepSize {Integer} 
   * @param customMessage {String} 
   * @param data {Array.<Number>} 
   */
  var exports = function(responseId, metricId, metricName, startIndex, endIndex, stepSize, customMessage, data) {
    var _this = this;

    _this['responseId'] = responseId;
    _this['metricId'] = metricId;
    _this['metricName'] = metricName;
    _this['startIndex'] = startIndex;
    _this['endIndex'] = endIndex;
    _this['stepSize'] = stepSize;
    _this['customMessage'] = customMessage;
    _this['data'] = data;
  };

  /**
   * Constructs a <code>Timeseries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Timeseries} obj Optional instance to populate.
   * @return {module:model/Timeseries} The populated <code>Timeseries</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('responseId')) {
        obj['responseId'] = ApiClient.convertToType(data['responseId'], 'Integer');
      }
      if (data.hasOwnProperty('metricId')) {
        obj['metricId'] = ApiClient.convertToType(data['metricId'], 'Integer');
      }
      if (data.hasOwnProperty('metricName')) {
        obj['metricName'] = ApiClient.convertToType(data['metricName'], 'String');
      }
      if (data.hasOwnProperty('startIndex')) {
        obj['startIndex'] = ApiClient.convertToType(data['startIndex'], 'Integer');
      }
      if (data.hasOwnProperty('endIndex')) {
        obj['endIndex'] = ApiClient.convertToType(data['endIndex'], 'Integer');
      }
      if (data.hasOwnProperty('stepSize')) {
        obj['stepSize'] = ApiClient.convertToType(data['stepSize'], 'Integer');
      }
      if (data.hasOwnProperty('customMessage')) {
        obj['customMessage'] = ApiClient.convertToType(data['customMessage'], 'String');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Integer} responseId
   */
  exports.prototype['responseId'] = undefined;
  /**
   * 
   * @member {Integer} metricId
   */
  exports.prototype['metricId'] = undefined;
  /**
   * 
   * @member {String} metricName
   */
  exports.prototype['metricName'] = undefined;
  /**
   * 
   * @member {Integer} startIndex
   */
  exports.prototype['startIndex'] = undefined;
  /**
   * 
   * @member {Integer} endIndex
   */
  exports.prototype['endIndex'] = undefined;
  /**
   * 
   * @member {Integer} stepSize
   */
  exports.prototype['stepSize'] = undefined;
  /**
   * 
   * @member {String} customMessage
   */
  exports.prototype['customMessage'] = undefined;
  /**
   * @member {Array.<Number>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


