/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Data'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Data'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.UserMetadataResponse = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Data);
  }
}(this, function(ApiClient, Data) {
  'use strict';




  /**
   * The UserMetadataResponse model module.
   * @module model/UserMetadataResponse
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>UserMetadataResponse</code>.
   * @alias module:model/UserMetadataResponse
   * @class
   * @param userId {String} 
   * @param data {module:model/Data} 
   */
  var exports = function(userId, data) {
    var _this = this;

    _this['user_id'] = userId;
    _this['data'] = data;
  };

  /**
   * Constructs a <code>UserMetadataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserMetadataResponse} obj Optional instance to populate.
   * @return {module:model/UserMetadataResponse} The populated <code>UserMetadataResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = Data.constructFromObject(data['data']);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * @member {module:model/Data} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


