/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Research', 'model/ResearchCreation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Research'), require('../model/ResearchCreation'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.ResearchApi = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Research, root.CrowdemotionApiClientJs.ResearchCreation);
  }
}(this, function(ApiClient, Research, ResearchCreation) {
  'use strict';

  /**
   * Research service.
   * @module api/ResearchApi
   * @version 1.1.0
   */

  /**
   * Constructs a new ResearchApi. 
   * @alias module:api/ResearchApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the researchGet operation.
     * @callback module:api/ResearchApi~researchGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Research>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find all Research
     * &lt;p&gt;Returns all the Research created by an admin user.&lt;/p&gt; &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.skip The number of results to skip.
     * @param {Integer} opts.limit The maximum number of results to return.
     * @param {String} opts.where JSON formatted string condition.
     * @param {String} opts.sort Attribute used to sort results.
     * @param {module:api/ResearchApi~researchGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Research>}
     */
    this.researchGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'where': opts['where'],
        'sort': opts['sort']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Research];

      return this.apiClient.callApi(
        '/research', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the researchPost operation.
     * @callback module:api/ResearchApi~researchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Research} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Research Project
     * &lt;p&gt;New research projects can only be created with an admin account.&lt;/p&gt; &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {module:model/ResearchCreation} body Request body
     * @param {module:api/ResearchApi~researchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Research}
     */
    this.researchPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling researchPost";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Research;

      return this.apiClient.callApi(
        '/research', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the researchResearchIdDelete operation.
     * @callback module:api/ResearchApi~researchResearchIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Research Project
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} researchId 
     * @param {module:api/ResearchApi~researchResearchIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {'String'}
     */
    this.researchResearchIdDelete = function(researchId, callback) {
      var postBody = null;

      // verify the required parameter 'researchId' is set
      if (researchId == undefined || researchId == null) {
        throw "Missing the required parameter 'researchId' when calling researchResearchIdDelete";
      }


      var pathParams = {
        'research_id': researchId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/research/{research_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the researchResearchIdGet operation.
     * @callback module:api/ResearchApi~researchResearchIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Research} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find a Research Project
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} researchId ID of Research Project to be found.
     * @param {module:api/ResearchApi~researchResearchIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Research}
     */
    this.researchResearchIdGet = function(researchId, callback) {
      var postBody = null;

      // verify the required parameter 'researchId' is set
      if (researchId == undefined || researchId == null) {
        throw "Missing the required parameter 'researchId' when calling researchResearchIdGet";
      }


      var pathParams = {
        'research_id': researchId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Research;

      return this.apiClient.callApi(
        '/research/{research_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the researchResearchIdPut operation.
     * @callback module:api/ResearchApi~researchResearchIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Research} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Research Project details
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} researchId 
     * @param {module:model/ResearchCreation} body Request body
     * @param {module:api/ResearchApi~researchResearchIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Research}
     */
    this.researchResearchIdPut = function(researchId, body, callback) {
      var postBody = body;

      // verify the required parameter 'researchId' is set
      if (researchId == undefined || researchId == null) {
        throw "Missing the required parameter 'researchId' when calling researchResearchIdPut";
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling researchResearchIdPut";
      }


      var pathParams = {
        'research_id': researchId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Research;

      return this.apiClient.callApi(
        '/research/{research_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
