/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Respondent', 'model/RespondentMetadataResponse', 'model/RespondentMetadata'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Respondent'), require('../model/RespondentMetadataResponse'), require('../model/RespondentMetadata'));
  } else {
    // Browser globals (root is window)
    if (!root.CrowdemotionApiClientJs) {
      root.CrowdemotionApiClientJs = {};
    }
    root.CrowdemotionApiClientJs.RespondentApi = factory(root.CrowdemotionApiClientJs.ApiClient, root.CrowdemotionApiClientJs.Respondent, root.CrowdemotionApiClientJs.RespondentMetadataResponse, root.CrowdemotionApiClientJs.RespondentMetadata);
  }
}(this, function(ApiClient, Respondent, RespondentMetadataResponse, RespondentMetadata) {
  'use strict';

  /**
   * Respondent service.
   * @module api/RespondentApi
   * @version 1.1.0
   */

  /**
   * Constructs a new RespondentApi. 
   * @alias module:api/RespondentApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the respondentGet operation.
     * @callback module:api/RespondentApi~respondentGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Respondent>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find all Respondents of a Research
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} researchId Search by research id.
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.skip The number of results to skip.
     * @param {Integer} opts.limit The maximum number of results to return.
     * @param {String} opts.where JSON formatted string.
     * @param {String} opts.sort Attribute used to sort results.
     * @param {module:api/RespondentApi~respondentGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Respondent>}
     */
    this.respondentGet = function(researchId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'researchId' is set
      if (researchId == undefined || researchId == null) {
        throw "Missing the required parameter 'researchId' when calling respondentGet";
      }


      var pathParams = {
      };
      var queryParams = {
        'research_id': researchId,
        'skip': opts['skip'],
        'limit': opts['limit'],
        'where': opts['where'],
        'sort': opts['sort']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Respondent];

      return this.apiClient.callApi(
        '/respondent', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentPost operation.
     * @callback module:api/RespondentApi~respondentPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Respondent} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a Respondent
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {module:model/Respondent} body Request body
     * @param {module:api/RespondentApi~respondentPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Respondent}
     */
    this.respondentPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling respondentPost";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Respondent;

      return this.apiClient.callApi(
        '/respondent', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentRespondentIdDelete operation.
     * @callback module:api/RespondentApi~respondentRespondentIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Respondent
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} respondentId 
     * @param {module:api/RespondentApi~respondentRespondentIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {'String'}
     */
    this.respondentRespondentIdDelete = function(respondentId, callback) {
      var postBody = null;

      // verify the required parameter 'respondentId' is set
      if (respondentId == undefined || respondentId == null) {
        throw "Missing the required parameter 'respondentId' when calling respondentRespondentIdDelete";
      }


      var pathParams = {
        'respondent_id': respondentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/respondent/{respondent_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentRespondentIdGet operation.
     * @callback module:api/RespondentApi~respondentRespondentIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Respondent} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find a Respondent
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} respondentId Search by research id.
     * @param {module:api/RespondentApi~respondentRespondentIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Respondent}
     */
    this.respondentRespondentIdGet = function(respondentId, callback) {
      var postBody = null;

      // verify the required parameter 'respondentId' is set
      if (respondentId == undefined || respondentId == null) {
        throw "Missing the required parameter 'respondentId' when calling respondentRespondentIdGet";
      }


      var pathParams = {
        'respondent_id': respondentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Respondent;

      return this.apiClient.callApi(
        '/respondent/{respondent_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentRespondentIdMetadataGet operation.
     * @callback module:api/RespondentApi~respondentRespondentIdMetadataGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RespondentMetadataResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find Respondent Metadata
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} respondentId ID of the Respondent
     * @param {module:api/RespondentApi~respondentRespondentIdMetadataGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/RespondentMetadataResponse}
     */
    this.respondentRespondentIdMetadataGet = function(respondentId, callback) {
      var postBody = null;

      // verify the required parameter 'respondentId' is set
      if (respondentId == undefined || respondentId == null) {
        throw "Missing the required parameter 'respondentId' when calling respondentRespondentIdMetadataGet";
      }


      var pathParams = {
        'respondent_id': respondentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = RespondentMetadataResponse;

      return this.apiClient.callApi(
        '/respondent/{respondent_id}/metadata', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentRespondentIdMetadataPost operation.
     * @callback module:api/RespondentApi~respondentRespondentIdMetadataPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RespondentMetadataResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Respondent Metadata
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} respondentId 
     * @param {module:model/RespondentMetadata} body Request body
     * @param {module:api/RespondentApi~respondentRespondentIdMetadataPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/RespondentMetadataResponse}
     */
    this.respondentRespondentIdMetadataPost = function(respondentId, body, callback) {
      var postBody = body;

      // verify the required parameter 'respondentId' is set
      if (respondentId == undefined || respondentId == null) {
        throw "Missing the required parameter 'respondentId' when calling respondentRespondentIdMetadataPost";
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling respondentRespondentIdMetadataPost";
      }


      var pathParams = {
        'respondent_id': respondentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = RespondentMetadataResponse;

      return this.apiClient.callApi(
        '/respondent/{respondent_id}/metadata', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the respondentRespondentIdPut operation.
     * @callback module:api/RespondentApi~respondentRespondentIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Respondent} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a Respondent
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     * @param {Integer} respondentId 
     * @param {module:model/Respondent} body Request body
     * @param {module:api/RespondentApi~respondentRespondentIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/Respondent}
     */
    this.respondentRespondentIdPut = function(respondentId, body, callback) {
      var postBody = body;

      // verify the required parameter 'respondentId' is set
      if (respondentId == undefined || respondentId == null) {
        throw "Missing the required parameter 'respondentId' when calling respondentRespondentIdPut";
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw "Missing the required parameter 'body' when calling respondentRespondentIdPut";
      }


      var pathParams = {
        'respondent_id': respondentId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Respondent;

      return this.apiClient.callApi(
        '/respondent/{respondent_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
