/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrowdemotionApiClientJs);
  }
}(this, function(expect, CrowdemotionApiClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrowdemotionApiClientJs.ContentDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentDetails', function() {
    it('should create an instance of ContentDetails', function() {
      // uncomment below and update the code to test ContentDetails
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be.a(CrowdemotionApiClientJs.ContentDetails);
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be();
    });

    it('should have the property dimension (base name: "dimension")', function() {
      // uncomment below and update the code to test the property dimension
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be();
    });

    it('should have the property definition (base name: "definition")', function() {
      // uncomment below and update the code to test the property definition
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be();
    });

    it('should have the property licensedContent (base name: "licensedContent")', function() {
      // uncomment below and update the code to test the property licensedContent
      //var instane = new CrowdemotionApiClientJs.ContentDetails();
      //expect(instance).to.be();
    });

  });

}));
