/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CrowdemotionApiClientJs);
  }
}(this, function(expect, CrowdemotionApiClientJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CrowdemotionApiClientJs.Media();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Media', function() {
    it('should create an instance of Media', function() {
      // uncomment below and update the code to test Media
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be.a(CrowdemotionApiClientJs.Media);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property mediaPath (base name: "mediaPath")', function() {
      // uncomment below and update the code to test the property mediaPath
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property researchId (base name: "researchId")', function() {
      // uncomment below and update the code to test the property researchId
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property timeCreated (base name: "timeCreated")', function() {
      // uncomment below and update the code to test the property timeCreated
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property lengthMS (base name: "lengthMS")', function() {
      // uncomment below and update the code to test the property lengthMS
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property length (base name: "length")', function() {
      // uncomment below and update the code to test the property length
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property videoOrder (base name: "videoOrder")', function() {
      // uncomment below and update the code to test the property videoOrder
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property presignedUrl (base name: "presignedUrl")', function() {
      // uncomment below and update the code to test the property presignedUrl
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property isStored (base name: "isStored")', function() {
      // uncomment below and update the code to test the property isStored
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property isURL (base name: "isURL")', function() {
      // uncomment below and update the code to test the property isURL
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property isYouTube (base name: "isYouTube")', function() {
      // uncomment below and update the code to test the property isYouTube
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property videodetails (base name: "videodetails")', function() {
      // uncomment below and update the code to test the property videodetails
      //var instane = new CrowdemotionApiClientJs.Media();
      //expect(instance).to.be();
    });

  });

}));
